/**
 * Typed loader for the design tokens (docs/TECH_DESIGN.md §10.2; D-003, R-04).
 *
 * `tokens.json` belongs to design-lead and is READ ONLY for code. This module validates it once with `zod/mini` and
 * exposes the parsed, deeply frozen object as `TOKENS`. A missing or malformed key throws at module load (a boot error
 * in development, TECH §10.2). The schema lists only paths that exist in tokens.json; `_doc` keys and the whole
 * `check.*` group are stripped (`check.*` is read by tests/theme/tokens.test.ts only, never by code).
 */
import * as z from 'zod/mini';
import rawTokens from './tokens.json' with { type: 'json' };
import { COLOR_CODES } from '../core/types.ts';

export const HEX_RE = /^#[0-9A-Fa-f]{6}$/;

const num = z.number();
const hex = z.string().check(z.regex(HEX_RE, 'expected #RRGGBB'));
const str = z.string();
const numList = z.array(num);

/** `{ [k]: schema }` for a fixed key list (typed, so every listed key is required and typed). */
function shapeOf<const K extends string, S extends z.ZodMiniType>(
  keys: readonly K[],
  schema: S,
): { [P in K]: S } {
  const out = {} as { [P in K]: S };
  for (const k of keys) out[k] = schema;
  return out;
}
const nums = <const K extends string>(keys: readonly K[]) => z.object(shapeOf(keys, num));
const hexes = <const K extends string>(keys: readonly K[]) => z.object(shapeOf(keys, hex));

const colorRecord = z.record(z.enum(COLOR_CODES), hex);

const ShadowSpec = z.object({ x: num, y: num, blur: num, color: hex, alpha: num });

const FONT_ROLES = ['display', 'h1', 'h2', 'button', 'body', 'small', 'caption'] as const;
const CHAPTERS = ['ch1', 'ch2', 'ch3', 'ch4', 'ch5'] as const;
const CHAPTER_COLORS = ['skyTop', 'skyBottom', 'cloud', 'far', 'mid', 'near'] as const;

const DURATION_KEYS = [
  'pick',
  'fingerOffset',
  'blockedShake',
  'bump',
  'craneEnter',
  'wallPass',
  'ghostSwitch',
  'cancel',
  'setYard',
  'land',
  'placeOk',
  'placeBad',
  'mortarStick',
  'streakPip',
  'combo',
  'goldTrowel',
  'segment',
  'scaffoldFade',
  'truck',
  'queue',
  'bounceToQueue',
  'reshuffle',
  'truckHelpUnchain',
  'truckHelpDeliver',
  'gapRail',
  'clamp',
  'gapSqueeze',
  'shutter',
  'tick',
  'slider',
  'paintGate',
  'unlock',
  'crateHit',
  'crateBreak',
  'bagTear',
  'chainBreak',
  'wetDry',
  'keyPickup',
  'screwCollect',
  'debris',
  'glassBreak',
  'balloonSettle',
  'steer',
  'carousel',
  'elevator',
  'reveal',
  'movesTick',
  'lastMovesPulse',
  'offer',
  'movesAdd',
  'goalDone',
  'siteClosedRibbon',
  'goalNudge',
  'win',
  'winGlow',
  'winRibbon',
  'winConfetti',
  'bonusPerMove',
  'bonusMax',
  'outOfMoves',
  'lifeLost',
  'starFly',
  'boosterSelect',
  'hammer',
  'craneBooster',
  'brush',
  'undo',
  'thermos',
  'trowelStart',
  'openShutter',
  'streakBonus',
  'buttonPress',
  'buttonRelease',
  'popupOpen',
  'popupClose',
  'tab',
  'lockedShake',
  'lockedHint',
  'coinFly',
  'townBuild',
  'bridgeStep',
  'bridgeFall',
  'rankMove',
  'splashLogo',
  'splashMin',
  'panelEnter',
  'ftuePanelAuto',
  'reducedFade',
  'tutorialHandLoop',
  'tutorialHandPause',
  'spotlightPulse',
  'loadingShowDelay',
  'hint',
  'supportFlash',
  'frontShift',
  'resumeToast',
  'chestLidOpen',
  'chestItemStagger',
  'dailyClaim',
  'ceilingSettle',
] as const;

/** ZzFX 1.4.0 `buildSamples` parameter list (≤ 21 values, tokens `audio._doc`). */
const ZzfxParams = z.array(num).check(z.maxLength(21));
const SFX_KEYS = [
  'sfx_pick',
  'sfx_blocked',
  'sfx_bump',
  'sfx_whoosh',
  'sfx_ghost_ok',
  'sfx_cancel',
  'sfx_set_yard',
  'sfx_fall',
  'sfx_land',
  'sfx_place_ok',
  'sfx_place_bad',
  'sfx_bounce',
  'sfx_queue',
  'sfx_offer',
  'sfx_coin',
  'sfx_life_lost',
  'sfx_button',
  'sfx_popup',
  'sfx_close',
  'sfx_tick',
  'sfx_streak_pip',
  'sfx_trowel',
  'sfx_clamp',
] as const;
const SEQ_KEYS = [
  'sfx_segment',
  'sfx_combo',
  'sfx_truck_horn',
  'sfx_lastmoves',
  'sfx_moves_add',
  'sfx_goal_done',
  'sfx_out_of_moves',
  'sfx_chest',
  'music_win',
  'sfx_gap_rail',
] as const;
/** `[startMs, params]` steps mixed into one buffer (TECH §11.6). */
const SeqSteps = z.array(z.tuple([num, ZzfxParams]));

export const TokensSchema = z.object({
  meta: z.object({
    version: num,
    owner: str,
    doc: str,
    designWidth: num,
    designHeight: num,
    designHeightMax: num,
    scale: nums(['fitHeight', 'expandMinHeight', 'expandMaxHeight']),
  }),
  color: z.object({
    block: colorRecord,
    planInk: colorRecord,
    ui: hexes([
      'panel',
      'panelInset',
      'panelEdge',
      'panelShadow',
      'ink',
      'inkSoft',
      'inkOnDark',
      'primary',
      'primaryTop',
      'primaryLip',
      'primaryStroke',
      'secondary',
      'secondaryTop',
      'secondaryLip',
      'secondaryStroke',
      'neutral',
      'neutralTop',
      'neutralLip',
      'neutralStroke',
      'danger',
      'dangerTop',
      'dangerLip',
      'dangerStroke',
      'disabled',
      'disabledLip',
      'tagHard',
      'tagSuperHard',
      'gold',
      'goldDark',
      'star',
      'starOutline',
      'heart',
      'hazardYellow',
      'hazardBlack',
      'overlay',
      'badge',
      'badgeLocked',
      'botBadge',
      'promoteLine',
      'demoteLine',
    ]),
    ghost: hexes(['valid', 'invalid', 'neutral', 'support']),
    board: hexes([
      'yardFloor',
      'yardFloorAlt',
      'yardGrid',
      'yardFrame',
      'blueprint',
      'blueprintDeep',
      'blueprintLine',
      'planUnderlay',
      'planEmptyHatch',
      'wall',
      'wallLight',
      'wallDark',
      'wallOutline',
      'scaffold',
      'scaffoldClamp',
      'craneSky',
      'craneLine',
      'rail',
      'narrowJaw',
      'shutterSlat',
      'shutterSlatLight',
      'sliderPlate',
      'lockBar',
      'buildFront',
    ]),
    obstacle: hexes([
      'crate',
      'crateLine',
      'crateOutline',
      'crateStrap',
      'cementBag',
      'cementBagOutline',
      'chain',
      'chainOutline',
      'wet',
      'mortar',
      'mortarOutline',
      'debris',
      'debrisCrack',
      'screw',
      'screwSlot',
      'key',
      'balloon',
    ]),
    chapter: z.object(shapeOf(CHAPTERS, hexes(CHAPTER_COLORS))),
    character: z.object({
      outline: hex,
      tuna: z.record(str, hex),
      dede: z.record(str, hex),
      kepce: z.record(str, hex),
      gribeton: z.record(str, hex),
      ayse: z.record(str, hex),
      selin: z.record(str, hex),
      riza: z.record(str, hex),
      kurdele: z.record(str, hex),
    }),
  }),
  alpha: nums([
    'overlay',
    'tutorialOverlay',
    'tutorialSoftOverlay',
    'symbolWhite',
    'planFill',
    'planInkLight',
    'planEmptyHatch',
    'planEmptyStroke',
    'blueprintLine',
    'blueprintLineMajor',
    'craneSky',
    'craneLine',
    'gloss',
    'seam',
    'ghostFill',
    'ghostNeutralStroke',
    'ghostGlow',
    'glassBody',
    'wetLayer',
    'segmentDoneScaffold',
    'panoramaFuture',
    'buildFrontGlow',
    'supportHatch',
  ]),
  block: z.object({
    ...shapeOf(
      [
        'insetRatio',
        'cornerRadiusRatio',
        'bevelTopRatio',
        'bevelTopLighten',
        'bevelLeftRatio',
        'bevelLeftLighten',
        'shadeBottomRatio',
        'shadeBottomFactor',
        'shadeRightRatio',
        'shadeRightFactor',
        'outlinePx',
        'outlineFactor',
        'seamPx',
        'seamFactor',
        'symbolSizeRatio',
        'symbolLightThresholdLstar',
        'symbolDarkFactor',
        'innerCornerRadiusRatio',
      ] as const,
      num,
    ),
    /** `[x, y, w, h]` as cell ratios (ART §3 layer 4). */
    glossRect: z.tuple([num, num, num, num]),
  }),
  plan: z.object({
    ...shapeOf(
      [
        'insetPx',
        'cornerRadiusRatio',
        'strokePx',
        'strokeFactor',
        'hatchSpacingPx',
        'hatchWidthPx',
        'hiddenTagPx',
        'frontStrokePx',
        'frontLighten',
        'supportHatchSpacingPx',
        'supportHatchWidthPx',
        'ceilingBeamPx',
      ] as const,
      num,
    ),
    /** `[dash, gap]` px. */
    dash: z.tuple([num, num]),
  }),
  layout: z.object({
    marginPx: num,
    grid: nums(['cellPx', 'yardX', 'yardCols', 'wallX', 'wallW', 'buildX', 'buildCols', 'rows', 'craneRows']),
    top: nums([
      'pauseX',
      'pauseY',
      'pauseSize',
      'panoramaX',
      'panoramaY',
      'panoramaW',
      'panoramaH',
      'goalsX',
      'goalsY',
      'goalsW',
      'goalsH',
      'movesX',
      'movesY',
      'movesW',
      'movesH',
      'topBarY',
      'topBarH',
      'groupBottomY',
    ]),
    board: nums([
      'craneTopY',
      'boardTopY',
      'boardBottomY',
      'statusY',
      'statusH',
      'statusBottomY',
      'minGapTopPx',
      'expandShare',
      'siteRibbonX',
      'siteRibbonY',
      'siteRibbonW',
      'siteRibbonH',
      'siteRibbonTiltDeg',
      'siteRibbonNotchPx',
    ]),
    bottom: nums([
      'characterX',
      'characterBottomPx',
      'characterW',
      'characterH',
      'boosterX',
      'boosterBottomPx',
      'boosterSize',
      'boosterGap',
      'navBottomPx',
      'navH',
      'playButtonW',
      'playButtonH',
      'playButtonBottomPx',
      'groupTopFromBottomPx',
    ]),
    popup: nums(['optionW', 'optionH', 'optionGap', 'optionsBottomInsetPx', 'panelBottomPx']),
  }),
  touch: nums(['minTargetPx', 'hitSlopPx']),
  drag: nums([
    'startThresholdPx',
    'holdMs',
    'liftScale',
    'fingerOffsetCells',
    'tiltMaxDeg',
    'trailMinSpeedCells',
    'tetherDelayMs',
    'tetherMinCells',
    'leanDeg',
    'bumpPx',
    'steerSwipeMinPx',
  ]),
  radius: nums(['button', 'panel', 'chip', 'badge', 'toggle', 'panelArt']),
  shadow: z.object({
    buttonLipPx: num,
    buttonPressedLipPx: num,
    panelLipPx: num,
    textOffsetY: num,
    contact: ShadowSpec,
    lifted: ShadowSpec,
    panel: ShadowSpec,
    crane: ShadowSpec,
  }),
  stroke: nums([
    'iconPx',
    'iconSmallPx',
    'ghostPx',
    'ghostInvalidPx',
    'ghostNeutralPx',
    'ghostGlowPx',
    'textEm',
  ]),
  font: z.object({
    family: str,
    fallback: z.array(str),
    size: nums(FONT_ROLES),
    weight: nums(FONT_ROLES),
    lineHeight: nums(FONT_ROLES),
  }),
  duration: nums(DURATION_KEYS),
  text: nums(['typewriterCps']),
  hud: nums(['heavyRingWarnAt', 'heavyRingHapticBeforeEndMs', 'steerChipPx']),
  easing: z.object(
    shapeOf(
      ['pop', 'move', 'moveIn', 'slide', 'settle', 'burst', 'bounce', 'elastic', 'fallIn', 'linear'],
      str,
    ),
  ),
  physics: nums([
    'fallNormalAccel',
    'fallNormalMax',
    'fallLowSpeed',
    'fallHighAccel',
    'fallHighMax',
    'yardFallAccel',
    'yardFallMax',
    'yardCascadeStaggerMs',
    'balloonRiseSpeed',
    'truckDropStaggerMs',
  ]),
  particles: nums([
    'maxOnScreen',
    'maxPerBurst',
    'reducedFactor',
    'land',
    'placeOk',
    'combo',
    'segment',
    'win',
    'winWaves',
    'glass',
    'crateBreak',
    'bagTear',
    'screw',
    'key',
  ]),
  haptic: z.object({
    light: num,
    medium: num,
    heavy: num,
    doubleLight: numList,
    success: numList,
    win: numList,
  }),
  audio: z.object({
    comboRootHz: num,
    comboSemitones: numList,
    sameSoundCooldownMs: num,
    maxVoices: num,
    musicDuckDb: num,
    sampleRateHz: num,
    prerenderBudgetMsPerFrame: num,
    sfx: z.object(shapeOf(SFX_KEYS, ZzfxParams)),
    seq: z.object(shapeOf(SEQ_KEYS, SeqSteps)),
  }),
  a11y: nums([
    'colorBlindSymbolScale',
    'colorBlindPlanFill',
    'colorBlindGhostBadgePx',
    'colorBlindGhostStrokeAddPx',
    'colorBlindSupportHatchPx',
    'colorBlindPaintSymbolScale',
    'colorBlindContrastBoost',
    'ghostBadgePx',
    'reducedScaleMax',
  ]),
});

/** Runtime tokens (no `check.*`, no `_doc`). */
export type Tokens = z.output<typeof TokensSchema>;

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const v of Object.values(value)) deepFreeze(v);
  }
  return value;
}

/** Validates raw token data; throws a readable error listing every missing or malformed path. */
export function parseTokens(raw: unknown): Tokens {
  const result = TokensSchema.safeParse(raw);
  if (!result.success) {
    throw new Error(
      `src/theme/tokens.json is invalid (TECH_DESIGN §10.2):\n${z.prettifyError(result.error)}`,
    );
  }
  return deepFreeze(result.data);
}

/** The validated design tokens. Throws at module load when tokens.json misses a required key. */
export const TOKENS: Tokens = parseTokens(rawTokens);
